name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - name: cargo-deny
      uses: EmbarkStudios/cargo-deny-action@v1.6.3
